export const FETCHING_TOKEN_DATA = 'FETCHING_TOKEN_DATA';
export const FETCHING_TOKEN_DATA_SUCCESS = 'FETCHING_TOKEN_DATA_SUCCESS';
export const FETCHING_TOKEN_DATA_FAIL = 'FETCHING_TOKEN_DATA_FAIL';
